services:
  - type: web
    name: portfolio-api
    env: node
    buildCommand: pnpm install --no-frozen-lockfile --ignore-scripts && pnpm -C artifacts/api-server run build
    startCommand: pnpm run start
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: run
        value: ${DATABASE_URL}
      - key: GMAIL_USER
        scope: run
        value: ${GMAIL_USER}
      - key: GMAIL_APP_PASSWORD
        scope: run
        value: ${GMAIL_APP_PASSWORD}
