uploads = []
outputs = []

[[generated]]
id = "ZRlejWSGmW41B5KtBwPbl"
uri = "file://artifacts/portfolio/src/assets/fuzzaiot.png"
type = "image"
title = "FuzzAIoT project thumbnail"

[[generated]]
id = "pdR3GHK0KxTOwW9M80dmj"
uri = "file://artifacts/portfolio/src/assets/imageify.png"
type = "image"
title = "Imageify project thumbnail"
